### ISSUE TITLE
base index.html?

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/files.opentreeoflife.org#4]
This is the `index.html` currently on files.opentreeoflife.org (though, not part of this repo):

```
<title>OTT 2.8 inputs</title>

See <a href="https://github.com/OpenTreeOfLife/reference-taxonomy/blob/ott2.8/doc/ott2.8.md">https://github.com/OpenTreeOfLife/reference-
taxonomy/blob/ott2.8/doc/ott2.8.md</a>
for an explanation.
```
1. Seems like this current file is out of place
2. What happened to the previous `index.html` that provided links to ott, newicks of the synthetic tree, etc.?
3. Why is `index.html` _not_ currently part of the repo?

**Comment by jimallman** [comment]
Yes, it looks like the most recent version of files.opentreeoflife.org has not yet been deployed to server `varela`. Have all of its contents been approved for production?

> What happened to the previous index.html that provided links to ott, newicks of the synthetic tree, etc.?

Are you thinking of [the Developer Resources page](https://tree.opentreeoflife.org/about/developer-resources), perhaps?

**Comment by josephwb** [comment]
That page is what I was thinking of, but I swear files.opentreeoflife.org had a similar (identical?) index.html. Maybe not.

**Comment by jar398** [comment]
As a temporary measure I made a little index.html consisting of a link to
the developer resources page.

Personally I don't like the idea of redirecting from the files site to the
webapp, as opposed to linking.
The webapp is going to be less robust, less archivable, less replicable,
more confusing, etc. than a static files site.
I guess if I'm the only one with these concerns maybe we should use the
redirects, but I think I'm going to hold off re-establishing the redirect
until after there's been a little discussion.

JWB, I recommend you bookmark the developer resources page.

**Comment by josephwb** [comment]
But why is `index.html`, whatever its content, not part of _this_ repo?
Probably some web deployment logic that will forever elude me. :dizzy_face:
Closing this, on the assumption that I'm an idiot.

**Comment by jar398** [comment]
Index.html wasn't in the repo because it didn't need to be because the file
was never accessed because there was an apache redirect in place that took
the browser directly to the webapp. https://en.wikipedia.org/wiki/HTTP_302

Formerly, there was an index.html file in the files.opentreeoflife.org
clone directory, but it was not in the repo. That file was garbage since it
was never seen by anyone.

I added a new little index.html to the repo last night for your benefit.
Maybe we will make that page a bit more respectable on a second iteration.
